{
    'name': 'Utility Core',
    'version': '16.0.1.0.0',
    'category': 'Industries/Utilities',
    'summary': 'Core Master Data for Utility ERP Platform',
    'description': """
Enterprise Utility Core Module
===============================
Master data management for national electricity distribution companies.
Manages customers, accounts, meters, tariffs, and network infrastructure.

Models: Company, Region, Area, Zone, Office, Feeder, Substation,
Transformer, Route, Customer, Account, Connection, Meter, Tariff, Staff, Team,
User Role.
    """,
    'author': 'Utility ERP Platform',
    'website': 'https://www.utility-erp.com',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'contacts', 'account', 'date_range', 'sale', 'payment'],
    'data': [
        'security/utility_security.xml',
        'security/ir.model.access.csv',
        'data/utility_sequence.xml',
        'data/utility_data.xml',
        'views/utility_region_views.xml',
        'views/utility_office_views.xml',
        'views/utility_feeder_views.xml',
        'views/utility_substation_views.xml',
        'views/utility_transformer_views.xml',
        'views/utility_route_views.xml',
        'views/utility_customer_views.xml',

        'views/utility_connection_views.xml',
        'views/utility_connection_type_views.xml',
        'views/utility_meter_views.xml',
        'views/utility_meter_type_views.xml',
        'views/utility_meter_model_views.xml',
        'views/utility_meter_status_views.xml',
        'views/utility_tariff_views.xml',
        'views/utility_tariff_category_views.xml',
        'views/utility_tariff_block_views.xml',
        'views/utility_tariff_history_views.xml',
        'views/utility_staff_views.xml',
        'views/utility_team_views.xml',
        'views/utility_user_role_views.xml',
        'views/utility_config_menu.xml',
        'views/utility_network_menu.xml',
        'views/utility_customer_wizard_views.xml',
        'views/utility_customer_menu.xml',
        'data/utility_subscriber_data.xml',
        'data/utility_sample_data.xml',
        'views/utility_subscriber_category_views.xml',
        'views/utility_subscriber_views.xml',
        'views/utility_date_range_views.xml',
        'views/utility_cell_reading_views.xml',
        'views/utility_contract_template_views.xml',
        'views/utility_contract_template_block_views.xml',
        'views/utility_contract_template_history_views.xml',
        'views/utility_settings_views.xml',
        'views/utility_res_users_views.xml',
        'views/sale_order_type_views.xml',
        'views/res_partner_sector_views.xml',
        'views/utility_res_partner_views.xml',
        'views/utility_meter_replacement_views.xml',
        'wizards/transformer_balance_wizard_views.xml',
        'wizards/formula_test_wizard_views.xml',
        'report/transformer_balance_report_template.xml',
        'report/transformer_balance_report.xml',
        'report/utility_receipt_report.xml',
    ],
    'demo': ['data/utility_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 10,
}
