{
    'name': 'Utility Billing',
    'version': '16.0.2.3.0',
    'category': 'Utility ERP',
    'summary': 'Postpaid Billing & Collections Engine (Sale Order Based)',
    'description': """
Enterprise Utility Billing Module
===================================
Postpaid billing engine with meter reading management,
billing cycles, sale order generation, penalty calculation,
debt management, collections, and online payment gateway integration.
    """,
    'author': 'Utility ERP Platform',
    'website': 'https://www.utility-erp.com',
    'license': 'LGPL-3',
    'depends': ['utility_core', 'utility_operations', 'account', 'sale', 'sale_management', 'sale_stock', 'portal'],
    'data': [
        'security/ir.model.access.csv',
        'security/utility_billing_security.xml',
        'data/utility_sequence.xml',
        'data/utility_cron.xml',
        'data/utility_cron_extras.xml',
        'data/utility_cron_batch.xml',
        'data/utility_billing_sample_data.xml',
        'views/utility_billing_menu.xml',
        'views/utility_service_charge_views.xml',
        'views/utility_reading_views.xml',
        'views/utility_reading_batch_views.xml',
        'views/utility_bill_reading_component_views.xml',
        'views/utility_sale_order_views.xml',
        'views/utility_sale_order_report.xml',
        'views/utility_customer_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/account_payment_report.xml',
        'views/utility_customer_statement_views.xml',
        'views/financial_settlement_views.xml',
        'views/utility_writeoff_views.xml',
        'views/utility_deposit_views.xml',
        'views/utility_penalty_views.xml',
        'views/utility_penalty_type_views.xml',
        'views/utility_billing_settings_views.xml',
        'views/utility_payment_gateway_views.xml',
        'views/utility_portal_templates.xml',
    ],
    'demo': ['data/utility_demo.xml'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 2,
}


